-- This Happy file was machine-generated by the BNF converter
{
{-# OPTIONS_GHC -fno-warn-incomplete-patterns -fno-warn-overlapping-patterns #-}
module ParCPP where
import AbsCPP
import LexCPP
import ErrM

}

%name pProgram Program
%name pListDef ListDef
%name pDef Def
%name pArg Arg
%name pListArg ListArg
%name pStm Stm
%name pDecl Decl
%name pListDecl ListDecl
%name pListStm ListStm
%name pExp16 Exp16
%name pListString ListString
%name pExp15 Exp15
%name pListQual ListQual
%name pListExp ListExp
%name pExp14 Exp14
%name pExp13 Exp13
%name pExp12 Exp12
%name pExp11 Exp11
%name pExp10 Exp10
%name pExp9 Exp9
%name pExp8 Exp8
%name pExp4 Exp4
%name pExp3 Exp3
%name pExp2 Exp2
%name pExp1 Exp1
%name pQual Qual
%name pListType ListType
%name pExp Exp
%name pExp5 Exp5
%name pExp6 Exp6
%name pExp7 Exp7
%name pType Type
%name pListId ListId
-- no lexer declaration
%monad { Err } { thenM } { returnM }
%tokentype {Token}
%token
  '!' { PT _ (TS _ 1) }
  '!=' { PT _ (TS _ 2) }
  '%' { PT _ (TS _ 3) }
  '&' { PT _ (TS _ 4) }
  '&&' { PT _ (TS _ 5) }
  '(' { PT _ (TS _ 6) }
  ')' { PT _ (TS _ 7) }
  '*' { PT _ (TS _ 8) }
  '+' { PT _ (TS _ 9) }
  '++' { PT _ (TS _ 10) }
  '+=' { PT _ (TS _ 11) }
  ',' { PT _ (TS _ 12) }
  '-' { PT _ (TS _ 13) }
  '--' { PT _ (TS _ 14) }
  '-=' { PT _ (TS _ 15) }
  '->' { PT _ (TS _ 16) }
  '.' { PT _ (TS _ 17) }
  '/' { PT _ (TS _ 18) }
  ':' { PT _ (TS _ 19) }
  '::' { PT _ (TS _ 20) }
  ';' { PT _ (TS _ 21) }
  '<' { PT _ (TS _ 22) }
  '<<' { PT _ (TS _ 23) }
  '<=' { PT _ (TS _ 24) }
  '=' { PT _ (TS _ 25) }
  '==' { PT _ (TS _ 26) }
  '>' { PT _ (TS _ 27) }
  '>=' { PT _ (TS _ 28) }
  '>>' { PT _ (TS _ 29) }
  '?' { PT _ (TS _ 30) }
  '[' { PT _ (TS _ 31) }
  ']' { PT _ (TS _ 32) }
  'bool' { PT _ (TS _ 33) }
  'const' { PT _ (TS _ 34) }
  'do' { PT _ (TS _ 35) }
  'double' { PT _ (TS _ 36) }
  'else' { PT _ (TS _ 37) }
  'false' { PT _ (TS _ 38) }
  'for' { PT _ (TS _ 39) }
  'if' { PT _ (TS _ 40) }
  'inline' { PT _ (TS _ 41) }
  'int' { PT _ (TS _ 42) }
  'return' { PT _ (TS _ 43) }
  'struct' { PT _ (TS _ 44) }
  'throw' { PT _ (TS _ 45) }
  'true' { PT _ (TS _ 46) }
  'typedef' { PT _ (TS _ 47) }
  'using' { PT _ (TS _ 48) }
  'void' { PT _ (TS _ 49) }
  'while' { PT _ (TS _ 50) }
  '{' { PT _ (TS _ 51) }
  '||' { PT _ (TS _ 52) }
  '}' { PT _ (TS _ 53) }

L_integ  { PT _ (TI $$) }
L_doubl  { PT _ (TD $$) }
L_charac { PT _ (TC $$) }
L_quoted { PT _ (TL $$) }
L_Id { PT _ (T_Id $$) }


%%

Integer :: { Integer } : L_integ  { (read ( $1)) :: Integer }
Double  :: { Double }  : L_doubl  { (read ( $1)) :: Double }
Char    :: { Char }    : L_charac { (read ( $1)) :: Char }
String  :: { String }  : L_quoted {  $1 }
Id    :: { Id} : L_Id { Id ($1)}

Program :: { Program }
Program : ListDef { AbsCPP.PDefs (reverse $1) }
ListDef :: { [Def] }
ListDef : {- empty -} { [] } | ListDef Def { flip (:) $1 $2 }
Def :: { Def }
Def : Type Id '(' ListArg ')' '{' ListStm '}' { AbsCPP.DFun $1 $2 $4 (reverse $7) }
    | 'inline' Type Id '(' ListArg ')' '{' ListStm '}' { AbsCPP.DFunInl $2 $3 $5 (reverse $8) }
    | Type Id '(' ListArg ')' ';' { AbsCPP.DFunProt $1 $2 $4 }
    | 'inline' Type Id '(' ListArg ')' ';' { AbsCPP.DFunProtInl $2 $3 $5 }
    | 'typedef' Type Id ';' { AbsCPP.DTypeDef $2 $3 }
    | Type ListId ';' { AbsCPP.DDecls $1 $2 }
    | Type Id '=' Exp ';' { AbsCPP.DInit $1 $2 $4 }
    | Type '&' Id '=' Exp ';' { AbsCPP.DInitRef $1 $3 $5 }
    | 'struct' Id '{' ListDecl '}' ';' { AbsCPP.DStruc $2 (reverse $4) }
    | 'using' ListQual ';' { AbsCPP.DUse $2 }
    | 'const' Def { AbsCPP.DConst $2 }
Arg :: { Arg }
Arg : Type { AbsCPP.ADeclBase $1 }
    | 'const' Type { AbsCPP.ADeclBaseCns $2 }
    | Type '&' { AbsCPP.ADeclBaseAdr $1 }
    | 'const' Type '&' { AbsCPP.ADeclBaseAdrCns $2 }
    | Type Id { AbsCPP.ADecl $1 $2 }
    | 'const' Type Id { AbsCPP.ADeclCns $2 $3 }
    | Type '&' Id { AbsCPP.ADeclAdr $1 $3 }
    | 'const' Type '&' Id { AbsCPP.ADeclAdrCns $2 $4 }
    | Type Id '=' Exp { AbsCPP.ADeclInit $1 $2 $4 }
    | 'const' Type Id '=' Exp { AbsCPP.ADeclInitCns $2 $3 $5 }
    | Type '&' Id '=' Exp { AbsCPP.ADeclInitAdr $1 $3 $5 }
    | 'const' Type '&' Id '=' Exp { AbsCPP.ADeclInitAdrCns $2 $4 $6 }
ListArg :: { [Arg] }
ListArg : {- empty -} { [] }
        | Arg { (:[]) $1 }
        | Arg ',' ListArg { (:) $1 $3 }
Stm :: { Stm }
Stm : Exp ';' { AbsCPP.SExp $1 }
    | Type ListId ';' { AbsCPP.SDecl $1 $2 }
    | Type Id '=' Exp ';' { AbsCPP.SInit $1 $2 $4 }
    | Type '&' Id '=' Exp ';' { AbsCPP.SInitRef $1 $3 $5 }
    | 'const' Type Id '=' Exp ';' { AbsCPP.SInitCnst $2 $3 $5 }
    | 'const' Type '&' Id '=' Exp ';' { AbsCPP.SInitCnstRef $2 $4 $6 }
    | 'typedef' Type Id ';' { AbsCPP.STypeDef $2 $3 }
    | 'struct' Id '{' ListDecl '}' ';' { AbsCPP.SStruc $2 (reverse $4) }
    | 'return' Exp ';' { AbsCPP.SReturn $2 }
    | 'while' '(' Exp ')' Stm { AbsCPP.SWhile $3 $5 }
    | 'do' Stm 'while' '(' Exp ')' ';' { AbsCPP.SDoWhile $2 $5 }
    | 'for' '(' Type Id ';' Exp ';' Exp ')' Stm { AbsCPP.SForDecl $3 $4 $6 $8 $10 }
    | 'for' '(' Type Id '=' Exp ';' Exp ';' Exp ')' Stm { AbsCPP.SForInit $3 $4 $6 $8 $10 $12 }
    | 'if' '(' Exp ')' Stm { AbsCPP.SIf $3 $5 }
    | 'if' '(' Exp ')' Stm 'else' Stm { AbsCPP.SIfElse $3 $5 $7 }
    | '{' ListStm '}' { AbsCPP.SBlock (reverse $2) }
Decl :: { Decl }
Decl : Type Id { AbsCPP.StructDecl $1 $2 }
ListDecl :: { [Decl] }
ListDecl : {- empty -} { [] }
         | ListDecl Decl ';' { flip (:) $1 $2 }
ListStm :: { [Stm] }
ListStm : {- empty -} { [] } | ListStm Stm { flip (:) $1 $2 }
Exp16 :: { Exp }
Exp16 : 'true' { AbsCPP.ETrue }
      | 'false' { AbsCPP.EFalse }
      | Integer { AbsCPP.EInt $1 }
      | Double { AbsCPP.EDouble $1 }
      | Char { AbsCPP.EChar $1 }
      | ListString { AbsCPP.EString $1 }
      | '(' Exp ')' { $2 }
ListString :: { [String] }
ListString : String { (:[]) $1 } | String ListString { (:) $1 $2 }
Exp15 :: { Exp }
Exp15 : Exp15 '[' Exp ']' { AbsCPP.EInd $1 $3 }
      | ListQual { AbsCPP.EQual $1 }
      | Exp15 '(' ListExp ')' { AbsCPP.EApp $1 $3 }
      | Exp16 { $1 }
ListQual :: { [Qual] }
ListQual : Qual { (:[]) $1 } | Qual '::' ListQual { (:) $1 $3 }
ListExp :: { [Exp] }
ListExp : {- empty -} { [] }
        | Exp { (:[]) $1 }
        | Exp ',' ListExp { (:) $1 $3 }
Exp14 :: { Exp }
Exp14 : Exp14 '.' Exp15 { AbsCPP.EStrProj $1 $3 }
      | Exp14 '->' Exp15 { AbsCPP.EStrProj2 $1 $3 }
      | Exp15 '++' { AbsCPP.EPostInc $1 }
      | Exp15 '--' { AbsCPP.EPostDec $1 }
      | '*' Exp15 { AbsCPP.EDeref $2 }
      | Exp15 { $1 }
Exp13 :: { Exp }
Exp13 : '++' Exp14 { AbsCPP.EPreInc $2 }
      | '--' Exp14 { AbsCPP.EPreDec $2 }
      | '!' Exp14 { AbsCPP.ENeg $2 }
      | Exp14 { $1 }
Exp12 :: { Exp }
Exp12 : Exp12 '*' Exp13 { AbsCPP.EMult $1 $3 }
      | Exp12 '/' Exp13 { AbsCPP.EDiv $1 $3 }
      | Exp12 '%' Exp13 { AbsCPP.EMod $1 $3 }
      | Exp13 { $1 }
Exp11 :: { Exp }
Exp11 : Exp11 '+' Exp12 { AbsCPP.EAdd $1 $3 }
      | Exp11 '-' Exp12 { AbsCPP.EDiff $1 $3 }
      | Exp12 { $1 }
Exp10 :: { Exp }
Exp10 : Exp10 '<<' Exp11 { AbsCPP.EShiftLeft $1 $3 }
      | Exp10 '>>' Exp11 { AbsCPP.EShiftRight $1 $3 }
      | Exp11 { $1 }
Exp9 :: { Exp }
Exp9 : Exp9 '<' Exp10 { AbsCPP.ELessThn $1 $3 }
     | Exp9 '>' Exp10 { AbsCPP.EGrtrThn $1 $3 }
     | Exp9 '<=' Exp10 { AbsCPP.ELessOrEq $1 $3 }
     | Exp9 '>=' Exp10 { AbsCPP.EGrtrOrEq $1 $3 }
     | Exp10 { $1 }
Exp8 :: { Exp }
Exp8 : Exp8 '==' Exp9 { AbsCPP.EEq $1 $3 }
     | Exp8 '!=' Exp9 { AbsCPP.ENEq $1 $3 }
     | Exp9 { $1 }
Exp4 :: { Exp }
Exp4 : Exp4 '&&' Exp5 { AbsCPP.EConj $1 $3 } | Exp5 { $1 }
Exp3 :: { Exp }
Exp3 : Exp3 '||' Exp4 { AbsCPP.EDisj $1 $3 } | Exp4 { $1 }
Exp2 :: { Exp }
Exp2 : Exp2 '=' Exp3 { AbsCPP.EAssign $1 $3 }
     | Exp2 '+=' Exp3 { AbsCPP.EAssignPlus $1 $3 }
     | Exp2 '-=' Exp3 { AbsCPP.EAssignPlus $1 $3 }
     | Exp2 '?' Exp3 ':' Exp3 { AbsCPP.ECond $1 $3 $5 }
     | Exp3 { $1 }
Exp1 :: { Exp }
Exp1 : 'throw' Exp1 { AbsCPP.EExp $2 } | Exp2 { $1 }
Qual :: { Qual }
Qual : Id '<' ListType '>' { AbsCPP.QTempl $1 $3 }
     | Id { AbsCPP.QDecl $1 }
ListType :: { [Type] }
ListType : Type { (:[]) $1 } | Type ',' ListType { (:) $1 $3 }
Exp :: { Exp }
Exp : Exp1 { $1 }
Exp5 :: { Exp }
Exp5 : Exp6 { $1 }
Exp6 :: { Exp }
Exp6 : Exp7 { $1 }
Exp7 :: { Exp }
Exp7 : Exp8 { $1 }
Type :: { Type }
Type : 'bool' { AbsCPP.Type_bool }
     | 'double' { AbsCPP.Type_double }
     | 'int' { AbsCPP.Type_int }
     | 'void' { AbsCPP.Type_void }
     | ListQual { AbsCPP.Type1 $1 }
ListId :: { [Id] }
ListId : Id { (:[]) $1 } | Id ',' ListId { (:) $1 $3 }
{

returnM :: a -> Err a
returnM = return

thenM :: Err a -> (a -> Err b) -> Err b
thenM = (>>=)

happyError :: [Token] -> Err a
happyError ts =
  Bad $ "syntax error at " ++ tokenPos ts ++ 
  case ts of
    [] -> []
    [Err _] -> " due to lexer error"
    _ -> " before " ++ unwords (map (id . prToken) (take 4 ts))

myLexer = tokens
}

